// Igual que en el panel de organizador: esta vista usa `style={{}}` inline,
// así que estas constantes son el equivalente en JS de los mismos tokens de
// `tailwind.config.ts` — una sola fuente de verdad para los colores.
export const colors = {
  background: '#101415',
  onBackground: '#e0e3e5',
  onSurfaceVariant: '#ccc3d8',
  onSurfaceFaintAlt: '#5a5270',
  outline: '#958da1',
  outlineVariant: '#4a4455',
  primary: '#d2bbff',
  onPrimary: '#3f008e',
  primaryContainer: '#7c3aed',
  primaryContainerDark: '#5b21b6',
  onPrimaryContainer: '#ede0ff',
  accentSecondary: '#4f35c7',
  surfaceContainer: '#1d2022',
  surfaceContainerLow: '#191c1e',
  surfaceContainerLowest: '#0b0f10',
  surfaceContainerHigh: '#272a2c',
  surfaceVariant: '#323537',
  surfaceCard: '#11151b',
  secondary: '#b4c5ff',
  secondaryContainer: '#0053db',
  onSecondaryContainer: '#cdd7ff',
  error: '#ffb4ab',
  success: '#4ade80',
  newsletterFrom: '#2f33a6',
  newsletterVia: '#1f2335',
  newsletterText: '#c3cbf7',
  white: '#ffffff',
} as const;
